const actionTypes = {
    ADD_CONTACT_SUCCESS: 'ADD_CONTACT_SUCCESS',
    LOAD_CONTACTLISTS_SUCCESS: 'LOAD_CONTACTLISTS_SUCCESS',
    UPDATE_CONTACT_SUCCESS: 'UPDATE_CONTACT_SUCCESS',
    DELETE_CONTACT_SUCCESS: 'DELETE_CONTACT_SUCCESS'
};

export default actionTypes;